comment: CM_dropout_721
cov_coeff: 1.0
dropout_rate_1: 0.25
dropout_rate_2: 0.25
encoder_start_lr: 0.0005
expander_factor: 1
pretrain_batch_size: 100
pretrain_epoch: 100
sim_coeff: 6.25
std_coeff: 6.25
warmup_epoch: 10
