comment: CM_dropout_680
cov_coeff: 1.0
dropout_rate_1: 0.5
dropout_rate_2: 1.0
encoder_start_lr: 0.001
expander_factor: 1
pretrain_batch_size: 400
pretrain_epoch: 10
sim_coeff: 6.25
std_coeff: 6.25
warmup_epoch: 2
