comment: CM_dropout_355
cov_coeff: 1.0
dropout_rate_1: 0.5
dropout_rate_2: 0.5
encoder_start_lr: 0.005
expander_factor: 2
pretrain_batch_size: 400
pretrain_epoch: 20
sim_coeff: 25.0
std_coeff: 25.0
warmup_epoch: 4
