comment: CM_dropout_242
cov_coeff: 1.0
dropout_rate_1: 0.25
dropout_rate_2: 0.25
encoder_start_lr: 0.0005
expander_factor: 2
pretrain_batch_size: 200
pretrain_epoch: 10
sim_coeff: 12.5
std_coeff: 12.5
warmup_epoch: 2
