comment: CM_dropout_228
cov_coeff: 1.0
dropout_rate_1: 0.5
dropout_rate_2: 0.5
encoder_start_lr: 0.001
expander_factor: 2
pretrain_batch_size: 100
pretrain_epoch: 10
sim_coeff: 12.5
std_coeff: 12.5
warmup_epoch: 2
