comment: CM_dropout_871
cov_coeff: 1.0
dropout_rate_1: 0.75
dropout_rate_2: 0.75
encoder_start_lr: 0.001
expander_factor: 4
pretrain_batch_size: 100
pretrain_epoch: 10
sim_coeff: 6.25
std_coeff: 6.25
warmup_epoch: 2
