comment: CM_dropout2d_367
cov_coeff: 1.0
dropout_rate_1: 0.5
dropout_rate_2: 0.5
encoder_start_lr: 0.0005
expander_factor: 4
pretrain_batch_size: 400
pretrain_epoch: 100
sim_coeff: 6.25
std_coeff: 6.25
warmup_epoch: 10
