comment: CM_dropout_90
cov_coeff: 1.0
dropout_rate_1: 0.25
dropout_rate_2: 0.25
encoder_start_lr: 0.005
expander_factor: 1
pretrain_batch_size: 100
pretrain_epoch: 20
sim_coeff: 12.5
std_coeff: 12.5
warmup_epoch: 4
