comment: CM_dropout_513
cov_coeff: 1.0
dropout_rate_1: 0.25
dropout_rate_2: 0.25
encoder_start_lr: 0.001
expander_factor: 4
pretrain_batch_size: 100
pretrain_epoch: 20
sim_coeff: 25.0
std_coeff: 25.0
warmup_epoch: 4
