comment: CM_dropout_144
cov_coeff: 1.0
dropout_rate_1: 0.5
dropout_rate_2: 1.0
encoder_start_lr: 0.005
expander_factor: 1
pretrain_batch_size: 400
pretrain_epoch: 20
sim_coeff: 12.5
std_coeff: 12.5
warmup_epoch: 4
