comment: CM_dropout_397
cov_coeff: 1.0
dropout_rate_1: 0.75
dropout_rate_2: 0.75
encoder_start_lr: 0.001
expander_factor: 2
pretrain_batch_size: 200
pretrain_epoch: 100
sim_coeff: 25.0
std_coeff: 25.0
warmup_epoch: 10
