comment: CM_dropout2d_104
cov_coeff: 1.0
dropout_rate_1: 0.25
dropout_rate_2: 0.75
encoder_start_lr: 0.0005
expander_factor: 1
pretrain_batch_size: 400
pretrain_epoch: 100
sim_coeff: 12.5
std_coeff: 12.5
warmup_epoch: 10
